create database NETFLIX_DB;
USE NETFLIX_DB;
SHOW tables;
-- CREATING THE TABLE STRUCTURE BASED ON DATA SET
CREATE TABLE IF NOT EXISTS NETFLIX_DATASET(
SHOW_ID INT,
TITLE VARCHAR(150),
DIRECTOR VARCHAR(200),
CAST TEXT,
COUNTRY VARCHAR(150),
DATE_ADDED VARCHAR(30),
RELEASED_YEAR VARCHAR(10),
RATING VARCHAR(10),
DURATION  VARCHAR(20),
CATEGORY_OF_MOVIE  TEXT,
DESCRIPTION_OF_MOVIE TEXT,
TYPE_OF_SHOW VARCHAR(100)

);
SHOW TABLES;
DESC NETFLIX_DATASET;
select count(*) from netflix_dataset;
SELECT * FROM NETFLIX_DATASET;
